const titleArr = [
  "Professional Linebacker Nick Kwiatkosi's Care for Real Toy Drive at the Shops at North Bridge",
  'Chicago Youth Symphony Orchestras\' 2020 Gala; "An American in Paris"',
  'Drink & Dance for Charity',
  'An Evening of Holiday Music - 6th Annual Dinner and Concert Gala',
  'Eosenopoly',
  'OCA-East Bay AAPI Leadership Lunch & Learns',
  'Warm Hearts with Donation',
  'Hillsdale Shopping Center Giving Tree Program',
  'Peninsula Humane Society - SPCA Pop Up Store',
  'The Fight For Air Climb',
  'Cat and Kitten Adoption Fair',
  'Ink for Paws 2',
  'Curl with Confidence',
  '15th Annual UNICEF Snowflake Ball',
  'Emergency Food Network Empty Bowls',
  'Winter Food Drive',
  'World AIDS Day RED RUN 2019',
  'Open Studio by Studio Upstairs',
  'Santa Dash 2019',
  'CASA Youth Advocates, Inc. 20th Annual Gala',
  'Pooch Kaboose Dog Adoption Event',
  "14th Annual Alex's Lemonade Stand Foundation Lemon Ball"
]

const descriptionArr = [
  'NFL linebacker Nick Kwiatkoski announced his third annual holiday toy drive in partnership with local Chicago charity Care for Real, alongside Shake Shack, the Shops at North Bridge, and Target. Kwiatkoski will be onsite at the center on Tuesday, December 10th from 12pm - 1pm for a meet and greet with fans who are participating in the drive. ',
  'Chicago Youth Symphony Orchestras\' 2020 gala celebrates the enduring Gershwin classic, "An American in Paris" and music of the legendary city of lights.Enjoy an evening of music and glamour to support world - class music education for young musicians from across the Chicago region.',
  'Join us for FREE dance lessons from The Lockport Swing Thing, music, and a good time. AND when you support people with developmental disabilities by donating $10 or more to Trinity Services',
  'From its beginnings in 1950 as a small school for children with disabilities, Trinity Services has grown to serve more than 3,500 children and adults with developmental disabilities and mental illness in DuPage, Cook, Will, Peoria, Grundy, Jackson, and St. Clair Counties.',
  "The unique and much anticipated event of the winter raises funds for the foundation's two - pronged mission: to fund gastrointestinal(GI) cancer research and to advance real estate education in an unforgettable, energy - filled evening.",
  'OCA-East Bay (ocaeastbay.org) is offering a FREE and exciting series of Leadership Lunch & Learns anchored by three incredible Asian Women Leaders. Please take a look at the descriptions and RSVP to ocaeastbay@gmail.com',
  'Hillsdale Shopping Center, in conjunction with the Ecumenical Hunger Program of East Palo Alto,  is warming up the holidays for needy Peninsula residents by participating in the One Warm Coat campaign.',
  'Together with Samaritan House of San Mateo County, Hillsdale Shopping Center is providing an opportunity for the San Mateo community to give back during the holiday season with the Giving Tree gift program. ',
  'The PHS/SPCA Holiday Pop Up Store and Adoption Center will offer pet related themed gifts and gifts for animal lovers. All proceeds from the sale of merchandise will benefit PHS/SPCA shelter animals.',
  "When you participate in a Fight For Air Climb event, you are stepping up to make a positive impact for those affected by lung disease. You will raise funds to support the American Lung Association's mission while climbing the stairs of a skyscraper.",
  "Want Kitties? We always have lots of kitties that are in need of good, loving homes. Please feel free to stop by, even if it's just for a cuddle!",
  "Join us for our 2nd Annual Ink for Paws! Last year was so much fun; you'll just have to drop in ! We are raising funds for One Love Dog Rescue, Inc. 501c3., so that we can continue our compassionate and fierce mission",
  'The TLC Foundation for BFRB (Body-focused Repetitive Behavior) is a general term for a group of related disorders that includes hair pulling, skin picking, and nail-biting. These behaviors are not habits or tics; rather, they are complex disorders that cause people to repeatedly touch their hair and body in ways that result in physical damage.',
  "UNICEF works in more than 190 countries and territories, helping save more children's lives than any other humanitarian organization. Since the inaugural UNICEF Snowflake Ball in 2005, the annual event has raised over $38 million for UNICEF's lifesaving programs.",
  'This event takes place during the Big Give Christmas Campaign and is a perfect way to learn more about what we do. Any donations made during the course of the week will be matched, doubling your impact!',
  'This Emergency Food Network event is an annual ritual enjoyed by more than 500 people each year.  During Empty Bowls, attendees can choose from more than 1,500 bowls to purchase for the home and for holiday gifts.',
  "Join us in helping to support our neighbors this holiday season. Peddler will be collecting non-perishable food items for the Ballard Food Bank and we'd love your help!",
  'Take Action. Lace Up!  The World AIDS Day RED RUN returns to Victoria Park on Sunday 30th November 2019 to raise awareness and funds for vital HIV services',
  'The dash starts at 11am, with entertainment between 10am - 2pm. Please note: whilst we welcome all ages to dash with us, from grandparents to babies, the 10k route is only available to anyone over 16 years old.',
  "In 1999, CASA was housed in a basement office that flooded frequently. The organization's 21 volunteers advocated for 83 Delaware County children on 42 cases, supported by a budget of $101, 000.There was no major fundraising event supporting the organization's work at the time.",
  'Come check out the adorable dogs looking for their FOREVER HOME!!! Event will be held at the Clubhouse next to the Leasing Office at The Towers At Wyncote.',
  "Complete with lemon yellow ties, heartwarming speeches by kids fighting cancer and fond remembrance of Alex Scott's lasting legacy, this annual event has inspired attendees since 2006."
]

const addressArr = [
  '4250 N Saint Louis Ave',
  '3711 W Douglas Blvd',
  '3244 W Ainslie St',
  '11710 S Morgan St',
  '644 W 71st St',
  '5625 N McVicker Ave',
  '1104 W 31st St',
  '620 N Sawyer Ave',
  '955 W Garfield Blvd',
  '720 N Lorel Ave',
  '8905 S Crandon Ave',
  '4247 W 15th St',
  '3849 W 69th Pl',
  '749 S Oakley Blvd',
  '1340 W Harrison St',
  '3149 N Wolcott Ave',
  '5650 N Mozart St',
  '3030 W Harrison St',
  '1420 W 17th St',
  '5608 W Washington Blvd',
  '1420 S Albany Ave',
  '1746 S Miller St',
  '9241 S Leavitt St',
  '6450 S Lowe Ave',
  '6700 N Greenview Ave',
  '5625 S Mobile Ave',
  '4647 W 47th St',
  '9351 S Lowe Ave',
  '1501 N Greenview Ave',
  '936 E 54th St',
  '1734 N Orleans St',
  '3500 W Douglas Blvd',
  '1424 N Cleaver St',
  '1431 N Leamington Ave',
  '5300 S Loomis Blvd',
  '615 W Kemper Pl',
  '3221 N Sacramento Ave',
  '2103 N Lamon Ave',
  '2828 N Oak Park Ave',
  '6333 W Bloomingdale Ave',
  '3320 W Hirsch St',
  '2941 N McVicker Ave',
  '7433 S Dorchester Ave',
  '1420 N Hudson Ave',
  '8050 S Chappel Ave',
  '6727 S California Ave',
  '6550 S Richmond St',
  '9822 S Exchange Ave',
  '4217 W 18th St',
  '2250 N Clifton Ave',
  '3527 S Wallace St',
  '6936 S Hermitage Ave',
  '2712 S Sawyer Ave',
  '4865 N Sheridan Rd',
  '8801 S Indiana Ave',
  '6901 S Fairfield Ave',
  '4728 N Wolcott Ave',
  '3937 W Wilcox St',
  '2233 W Ohio St',
  '4415 S Dr Martin L King Jr Dr',
  '3651 W Schubert Ave',
  '1711 N California Ave',
  '6011 S Rockwell St',
  '851 W Waveland Ave',
  '5235 W Belden St',
  '10841 S Homan Ave',
  '10540 S Morgan St',
  '2200 N Hamlin Ave',
  '3539 W Grace St',
  '5335 S Kenwood Ave',
  '12607 S Union Ave',
  '4837 W Erie St',
  '8555 S Michigan Ave',
  '11816 S Indiana Ave',
  '3252 N Broadway St',
  '700 W Willow St',
  '901 E 133rd Pl',
  '5250 S Rockwell St',
  '2121 N Keeler Ave',
  '4127 W Hirsch St',
  '5900 N Nina Ave',
  '24 W Walton St',
  '7646 S Green St',
  '6940 S Merrill Ave',
  '6634 W Raven St',
  '5424 N Oketo Ave',
  '1040 N Keeler Ave',
  '525 N Armour St',
  '6550 S Seeley Ave',
  '8247 S Christiana Ave',
  '3711 W Douglas Blvd',
  '5051 N Kenneth Ave',
  '6800 S Stewart Ave',
  '7037 S Rhodes Ave',
  '6938 S East End Ave',
  '5825 S Kostner Ave',
  '3826 W 58th St',
  '1423 W Bryn Mawr Ave',
  '1616 S Avers Ave',
  '9130 S University Ave',
  '3200 S Calumet Ave'
]

module.exports = {descriptionArr, titleArr, addressArr}
